name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  flutter_test:
    name: Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: flutter_test
    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Install dependencies
        run: flutter pub get
        run: flutter clean

      - name: Build APK
        run: flutter build apk --release

  build_ios:
    name: Build iOS
    runs-on: macos-latest
    needs: flutter_test   
    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Install dependencies
        run: flutter pub get
        run: flutter clean

      - name: Build iOS
        run: flutter build ios --release --no-codesign

